name: Java CI with Maven
on: 
  workflow_dispatch:
env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSKEY }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}         
jobs:
  startrunner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.readid.outputs.runner }}
      runnerflag: ${{ steps.readid.outputs.flag }}
    steps:
      - uses: actions/checkout@v3
      - id: readid
        run: |
           aws s3 cp s3://awsinstanceid/InstanceID.txt ${{github.workspace}}/InstanceID1.txt
           input='${{github.workspace}}/InstanceID1.txt'
           while IFS= read -r line
           do
             echo "$line"
             status=$(aws ec2 describe-instance-status --instance-id $line | jq -r '.InstanceStatuses[] | .InstanceState | .Name')
             if [ "$status" != "running" ];then
               aws ec2 start-instances --instance-ids $line
               echo "::set-output name=runner::$line"
               echo "::set-output name=flag::true"
               break
             fi
             echo "::set-output name=flag::false"
           done < "$input"
           sleep 60
          
           
#   Runner-status-check:
#     needs: startrunner
#     runs-on: ubuntu-latest
#     if: ${{ needs.startrunner.outputs.flag }} == 'false'
    
    
  build:
     needs: startrunner
     runs-on: self-hosted
     steps:
        - run: |
           echo "Hello World"
           sleep 180
           
#   stop_runner:
#     needs: [build, startrunner]
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           aws ec2 stop-instances --instance-ids ${{ needs.startrunner.outputs.runner }}
